// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Real secrets live in .env.local (Next.js convention), not .env.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // This `url` is only used by the Prisma CLI (migrate/generate/studio) — the
  // generated Client never reads it, since the driver adapter in lib/db.ts
  // supplies its own connection string (DATABASE_URL, pooled) at runtime.
  // DIRECT_URL bypasses Neon's pooler, which the schema engine prefers for
  // migrations. (This Prisma version's config has no separate `directUrl`
  // field, unlike schema.prisma's old `directUrl` datasource attribute.)
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
