import "server-only";
import { Document, Page, Text, View, Image, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { StoryBlock } from "@/lib/llm/schemas";
import { accentFor, chartDataUri, type NarrationExportData } from "./types";

const styles = StyleSheet.create({
  page: {
    paddingTop: 70,
    paddingBottom: 70,
    paddingHorizontal: 56,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
    fontSize: 12,
    lineHeight: 1.6,
  },
  brandHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 2,
  },
  brandLogo: { height: 32 },
  brandName: { fontSize: 13, fontWeight: 600, color: "#6b7280" },
  // lineHeight must be set explicitly here, not inherited from `page` — when
  // inherited, React-PDF carries down the *computed* line height in points
  // rather than the multiplier, which is far too tight once fontSize jumps
  // from 12px to 28px and causes wrapped heading lines to overlap.
  h1: { fontSize: 28, marginBottom: 8, fontWeight: 700, lineHeight: 1.3 },
  h2: { fontSize: 18, marginTop: 32, marginBottom: 10, fontWeight: 700, lineHeight: 1.3 },
  p: { fontSize: 12, marginBottom: 12, lineHeight: 1.6 },
  listItem: { fontSize: 12, marginBottom: 6, paddingLeft: 16 },
  chartImage: { width: 340, marginVertical: 12 },
  footer: { marginTop: 48, fontSize: 10, color: "#9ca3af" },
});

function Blocks({ blocks, findings, accent }: { blocks: StoryBlock[]; findings: NarrationExportData["findings"]; accent: string }) {
  return (
    <>
      {blocks.map((block, i) => {
        if (block.type === "heading") {
          return (
            <Text key={i} style={[block.level === 1 ? styles.h1 : styles.h2, { color: accent }]}>
              {block.text}
            </Text>
          );
        }
        if (block.type === "paragraph") {
          return (
            <Text key={i} style={styles.p}>
              {block.text}
            </Text>
          );
        }
        if (block.type === "list") {
          return (
            <View key={i} style={{ marginBottom: 12 }}>
              {block.items.map((item, j) => (
                <Text key={j} style={styles.listItem}>
                  • {item}
                </Text>
              ))}
            </View>
          );
        }
        // chart
        const uri = chartDataUri(findings, block.findingRef);
        return uri ? <Image key={i} src={uri} style={styles.chartImage} /> : null;
      })}
    </>
  );
}

function ReportDocument({ title, blocks, findings, brand }: NarrationExportData) {
  const accent = accentFor(brand);
  const showLogo = brand.isBranded && brand.logoUrl;
  const showBrandName = !showLogo;

  return (
    <Document title={title}>
      <Page size="A4" style={styles.page}>
        <View style={[styles.brandHeader, { borderBottomColor: accent }]}>
          {showLogo ? (
            // eslint-disable-next-line jsx-a11y/alt-text
            <Image src={brand.logoUrl as string} style={styles.brandLogo} />
          ) : showBrandName ? (
            <Text style={styles.brandName}>DataBrief</Text>
          ) : null}
        </View>

        <Blocks blocks={blocks} findings={findings} accent={accent} />

        <Text style={styles.footer}>Generated by DataBrief</Text>
      </Page>
    </Document>
  );
}

export async function renderReportPdf(data: NarrationExportData): Promise<Buffer> {
  return renderToBuffer(<ReportDocument {...data} />);
}
