from pathlib import Path

from src.core.config import settings
from src.models.report import Report
from src.models.user import User

PDF_CSS = """
@page {{ size: A4; margin: 2.5cm 2cm; }}
body {{ font-family: 'DejaVu Sans', Arial, sans-serif; color: #1a1a1a; line-height: 1.6; }}
h1 {{ font-size: 28px; color: {accent}; margin-bottom: 8px; }}
h2 {{ font-size: 18px; color: {accent}; margin-top: 32px; margin-bottom: 10px; }}
p {{ font-size: 12px; margin: 0 0 12px; }}
ul {{ margin: 0 0 12px; padding-left: 20px; }}
li {{ font-size: 12px; margin-bottom: 6px; }}
.brand-header {{ display: flex; align-items: center; gap: 12px; margin-bottom: 24px; border-bottom: 2px solid {accent}; padding-bottom: 12px; }}
.brand-header img {{ height: 32px; }}
.brand-header span {{ font-size: 13px; font-weight: 600; color: #6b7280; }}
.footer {{ margin-top: 48px; font-size: 10px; color: #9ca3af; }}
"""


def _output_dir(report_id: str) -> Path:
    out_dir = Path(settings.upload_dir) / "reports" / report_id
    out_dir.mkdir(parents=True, exist_ok=True)
    return out_dir


def build_pdf(report: Report, user: User) -> str:
    from weasyprint import HTML

    accent = user.brand_primary if (report.is_branded and user.brand_primary) else "#2563eb"
    brand_name = "DataBrief" if not (report.is_branded and user.brand_logo_url) else None

    header = ""
    if report.is_branded and user.brand_logo_url:
        header = f'<div class="brand-header"><img src="{user.brand_logo_url}" /></div>'
    elif brand_name:
        header = f'<div class="brand-header"><span>{brand_name}</span></div>'

    html_doc = f"""
    <html>
      <head><meta charset="utf-8" /><style>{PDF_CSS.format(accent=accent)}</style></head>
      <body>
        {header}
        {report.story_html or ""}
        <div class="footer">Generated by DataBrief</div>
      </body>
    </html>
    """

    from src.services import storage_service
    import tempfile, os
    if storage_service._r2_configured():
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
        tmp.close()
        HTML(string=html_doc).write_pdf(tmp.name)
        object_key = f"reports/{report.id}/report.pdf"
        storage_service.upload_file(tmp.name, object_key, content_type="application/pdf")
        os.remove(tmp.name)
        return object_key
    out_path = _output_dir(str(report.id)) / "report.pdf"
    HTML(string=html_doc).write_pdf(str(out_path))
    return str(out_path)
