"""cascade deletes on uploads and reports

Revision ID: 273f0710351f
Revises: d4a0b113bac0
Create Date: 2026-06-30 10:30:41.355963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '273f0710351f'
down_revision: Union[str, None] = 'd4a0b113bac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_upload_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uploads_user_id_fkey', 'uploads', type_='foreignkey')
    op.create_foreign_key(None, 'uploads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.create_foreign_key('uploads_user_id_fkey', 'uploads', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_upload_id_fkey', 'reports', 'uploads', ['upload_id'], ['id'])
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
